spring.application.name=Smart_Shelf_Project
spring.datasource.url=jdbc:mysql://localhost:3306/vgse
spring.datasource.username=root
spring.datasource.password=@raj8464091858
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=TRACE
spring.web.resources.static-locations=file:uploads/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nagamraju457@gmail.com
spring.mail.password=mbytlwglpzsdcgvn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB